### PR TITLE
Feature/adding server files

### PR DESCRIPTION
**Pull request by kelsiesmurphy**

### CODE REVIEW

**Comment by AndromedaMedi** [comment]
should that not be pushed to the dev branch instead of main?

**Comment by kelsiesmurphy** [comment]
> should that not be pushed to the dev branch instead of main?

Yep, i'm not sure why its done that, i did `git push origin dev`, and I created the branch from dev. Should I be doing something else?

**Comment by kelsiesmurphy** [comment]
I'm gonna close this and try again from beginning hehe

**Comment by AndromedaMedi** [comment]
when you're making the request here you need to change it from main to dev somewhere at the top left of the window

**Comment by kelsiesmurphy** [comment]
okay will try that lol

**Pull request closed without merging**
